config/routes.rb
EaseApp::Application.routes.draw do
  
  root to:'static_pages#home'

  
  match '/about', to:'static_pages#about' 
  match '/getInvolved', to:'static_pages#getInvolved'
  match '/members', to:'static_pages#members'
  match '/partners', to:'static_pages#partners'
  match '/events', to:'static_pages#events'
  match '/gallery', to:'static_pages#gallery'
  match '/faqs', to:'static_pages#faqs'
  match '/contact', to:'static_pages#contact'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def members
  end

  def partners
  end

  def getInvolved
  end

  def gallery
  end

  def events
  end

  def faqs
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> EASE | Expediting Access to Standard Education | <%= yield(:title)%></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
>
<div class="contianer">

	<header id = "head">

		<h1> E.A.S.E</h1>
		<h2>Expediting Access to Standard Education</h2>
		<div id="head-inner"></div>

	</header>
	<!--<div class= "spacer"> </div>-->
<!--	<nav class= "menu">
		<ul>
			<li class = "menuitem-grower"><%= link_to("Home", '/static_pages/home')%></li>
			<li class = "menuitem-grower"><%= link_to("About Us", '/static_pages/about')%></li>
			<li class = "menuitem-grower"><%= link_to("Get Involved", '/static_pages/getInvolved')%>
			 	<ul>
					<li><%= link_to("Board Members", '/static_pages/members')%></li>
					<li><%= link_to("Partners", '/static_pages/partners')%></li>
				</ul> 
			</li>
			<li class = "menuitem-grower"><%= link_to("Events", '/static_pages/events')%></li>
			<li class = "menuitem-grower"><%= link_to("Gallery", '/static_pages/gallery')%></li>
			<li class = "menuitem-grower"><%= link_to("FAQs", '/static_pages/faqs')%></li>
			<li class = "menuitem-grower"><%= link_to("Contact Us", '/static_pages/contact')%></li>
			

		</ul>
	</nav> --> 
	
<!--		<div id="navcontainer">
			<ul id="navlist">

				<li><%= link_to "Home", { :controller => 'static_pages', :action => 'home' }, :class => 'current' -%> </li>
				<li><%= link_to("About Us", '/static_pages/about')%></li>
				<li><%= link_to("Get Involved", '/static_pages/getInvolved')%></li>
				<li><%= link_to("Events", '/static_pages/events')%></li>
				<li><%= link_to("Gallery", '/static_pages/gallery')%></li>
				<li><%= link_to("FAQs", '/static_pages/faqs')%></li>
				<li><%= link_to("Contact Us", '/static_pages/contact')%></li>
			
			</ul>
		</div> -->

</div> 

 <div class="content">
	<%= yield %>
</div> 


<footer id = "foot">
	<div class= "spacer"> </div>
	<ul id = "foot-navlist">

				<li><%= link_to("IDEAS Grant Proposal |", '#')%></li>
				<li><%= link_to("Constitution |", '#')%></li>
				<li><%= link_to("EASE Brochure", '#')%></li>
			</ul>

			<div id="foot-inner">
			
		</div>
</footer>



</body>
</html>

app/views/static_pages/about.html.erb
<%provide(:title, 'About Us')%>

		<div id="navcontainer">
			<ul id="navlist">

				<li><%= link_to "Home", root_path%> </li>
				<li><%= link_to "About Us", about_path, :class => 'current' %> </li>
				<li><%= link_to("Get Involved", getInvolved_path)%></li>
				<li><%= link_to "Partners", partners_path%></li>
				<li><%= link_to "Board Members", members_path%></li>
				<li><%= link_to("Events", events_path)%></li>
				<li><%= link_to("Gallery", gallery_path)%></li>
				<li><%= link_to("FAQs", faqs_path)%></li>
				<li><%= link_to("Contact Us", contact_path)%></li>
			
			</ul>
		</div>
<div class = "spacer"></div>
<p>
EASE is an acronym for Expediting Access to Standard Education. The aim of the program is to improve access to basic education in Africa through sponsorship programs and the establishment of libraries in villages. We believe that education holds the solution to most of the world's problems. Yet, many children are denied the opportunity due to financial constraints. We are convinced that a little effort on our part will go a long way to help.
</p>

<br>

<p>Although the program has hopes of expanding to other African countries, the initial scope is limited to Ghana and Nigeria. The current focus is to sponsor underprivileged children through Junior Secondary School (JSS), which forms the core of basic education in Ghana and then tentative of the students performance, continue this sponsorship through Senior Secondary School (SSS). EASE’s objectives are:
</p>

<br>
<ul>
<li>To raise awareness at MIT and surrounding institutions about the effect of domestic financial constraints on the accessibility to basic education in developing African countries </li>
<br>
<li>To improve access to basic education by financially sponsoring underprivileged students in Africa to attend their equivalent Junior and Senior High School</li>
<br>
<li>To promote cooperation with other international development-focused organizations</li>
<br>
<li>To help selected villages/schools establish community libraries/stock existing ones</li>
<br>
<li>To extend EASE Operations to other colleges besides MIT</li>
<br>
<li>To extend EASE Sponsorship and Operations to other African countries</li>
<br>
<li>To act on other matters related to the aims and objectives as stated above</li>
	
</ul>

app/views/static_pages/contact.html.erb
<%provide(:title, 'Contact')%>

		<div id="navcontainer">
			<ul id="navlist">

				<li><%= link_to "Home", root_path%> </li>
				<li><%= link_to("About Us", about_path)%></li>
				<li><%= link_to("Get Involved", getInvolved_path)%></li>
				<li><%= link_to "Partners", partners_path%></li>
				<li><%= link_to "Board Members", members_path%></li>
				<li><%= link_to("Events", events_path)%></li>
				<li><%= link_to("Gallery", gallery_path)%></li>
				<li><%= link_to("FAQs", faqs_path)%></li>
				<li><%= link_to"Contact Us", contact_path , :class => 'current'%></li>
			
			</ul>
		</div>
		<div class = "spacer"></div>

app/views/static_pages/events.html.erb
<%provide(:title, 'Events')%>

		<div id="navcontainer">
			<ul id="navlist">

				<li><%= link_to "Home", root_path %> </li>
				<li><%= link_to("About Us", about_path)%></li>
				<li><%= link_to("Get Involved", getInvolved_path)%></li>
				<li><%= link_to "Partners", partners_path%></li>
				<li><%= link_to "Board Members", members_path%></li>
				<li><%= link_to"Events", events_path, class: 'current'%></li>
				<li><%= link_to("Gallery", gallery_path)%></li>
				<li><%= link_to("FAQs", faqs_path)%></li>
				<li><%= link_to("Contact Us", contact_path)%></li>
			
			</ul>
		</div>
		<div class = "spacer"></div>

app/views/static_pages/faqs.html.erb
<%provide(:title, 'FAQs')%>

		<div id="navcontainer">
			<ul id="navlist">

				<li><%= link_to "Home", root_path%> </li>
				<li><%= link_to("About Us", about_path)%></li>
				<li><%= link_to("Get Involved", getInvolved_path)%></li>
				<li><%= link_to "Partners", partners_path%></li>
				<li><%= link_to "Board Members", members_path%></li>
				<li><%= link_to("Events", events_path)%></li>
				<li><%= link_to("Gallery", gallery_path)%></li>
				<li><%= link_to"FAQs", faqs_path, class: 'current'%></li>
				<li><%= link_to("Contact Us", contact_path)%></li>
			
			</ul>
		</div>
		<div class = "spacer"></div>

app/views/static_pages/gallery.html.erb
<%provide(:title, 'Gallery')%>


		<div id="navcontainer">
			<ul id="navlist">

				<li><%= link_to "Home", root_path%> </li>
				<li><%= link_to("About Us", about_path)%></li>
				<li><%= link_to("Get Involved", getInvolved_path)%></li>
				<li><%= link_to "Partners", partners_path%></li>
				<li><%= link_to "Board Members", members_path%></li>
				<li><%= link_to("Events", events_path)%></li>
				<li><%= link_to "Gallery", gallery_path, :class => 'current' -%> </li>
				<li><%= link_to("FAQs", faqs_path)%></li>
				<li><%= link_to("Contact Us", contact_path)%></li>
			
			</ul>
		</div>
		<div class = "spacer"></div>

<p>Find me in app/views/static_pages/gallery.html.erb</p>

app/views/static_pages/getInvolved.html.erb
<%provide(:title, 'Get Involved')%>


		<div id="navcontainer">
			<ul id="navlist">

				<li><%= link_to "Home", root_path %> </li>
				<li><%= link_to("About Us", about_path)%></li>
				<li><%= link_to "Get Involved", getInvolved_path, :class => 'current' %> </li>
				<li><%= link_to "Partners", partners_path%></li>
				<li><%= link_to "Board Members", members_path%></li>
				<li><%= link_to("Events", events_path)%></li>
				<li><%= link_to("Gallery", gallery_path)%></li>
				<li><%= link_to("FAQs", faqs_path)%></li>
				<li><%= link_to("Contact Us", contact_path)%></li>
			
			</ul>
		</div>
		<div class = "spacer"></div>
<p>Find me in app/views/static_pages/getInvolved.html.erb</p>

app/views/static_pages/home.html.erb
<%provide(:title, 'Home')%>

		<div id="navcontainer">
			<ul id="navlist">

				<li><%= link_to "Home", root_path, :class => 'current' -%> </li>
				<li><%= link_to("About Us", about_path)%></li>
				<li><%= link_to("Get Involved", getInvolved_path)%></li>
				<li><%= link_to "Partners", partners_path%></li>
				<li><%= link_to "Board Members", members_path%></li>
				<li><%= link_to("Events", events_path)%></li>
				<li><%= link_to("Gallery", gallery_path)%></li>
				<li><%= link_to("FAQs", faqs_path)%></li>
				<li><%= link_to("Contact Us", contact_path)%></li>
			
			</ul>
		</div>
<div class = "spacer"></div>
<div id = "center-image">
<%= link_to image_tag("blackboard.jpg", alt: "Rails"), '/assets/images/blackboard.jpg' %>

</div>

<div class ="spacer"></div>	
<h3> Welcome!</h3>
<p>Great news, you can now donate to EASE through the MIT Giving Website! <p>

<p> Every year, millions of children in Africa are denied access to basic education due to poverty! </p>

<p>EASE is an MIT-student initiative founded with the primary aim of making basic education more accessible to underprivileged children in Africa. We realize that this is a enormous task, but as the wise will say, a journey of a hundred years begins with one step. </p>

<p>Supporting child education since April, 2002 </p>

<p>Explore this site to learn more about how you can help.</p>

<div class= "progress">
<h4>News Item Title</h4>
<<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam at justo neque. Praesent libero quam, tempor sed facilisis eget, fermentum id velit. Nullam blandit felis vel risus semper sodales tincidunt leo vestibulum. Donec at neque vitae velit auctor tincidunt at sit amet leo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque sed nunc id tortor adipiscing gravida. Nunc eu lacus ut quam semper adipiscing et non orci. Etiam luctus scelerisque neque sit amet convallis. Cras arcu ante, luctus sed fringilla ut, sodales sit amet mi.</p>
</div>

app/views/static_pages/members.html.erb
<%provide(:title, 'Board Members')%>

		<div id="navcontainer">
			<ul id="navlist">

				<li><%= link_to "Home", root_path %> </li>
				<li><%= link_to("About Us", about_path)%></li>
				<li><%= link_to("Get Involved", getInvolved_path)%></li>
				<li><%= link_to "Partners", partners_path%></li>
				<li><%= link_to "Board Members", members_path , :class => 'current'%></li>
				<li><%= link_to("Events", events_path)%></li>
				<li><%= link_to("Gallery", gallery_path)%></li>
				<li><%= link_to("FAQs", faqs_path)%></li>
				<li><%= link_to("Contact Us", contact_path)%></li>
			
			</ul>
		</div>
		<div class = "spacer"></div>
<p>Find me in app/views/static_pages/members.html.erb</p>

app/views/static_pages/partners.html.erb
<%provide(:title, 'Partners')%>

		<div id="navcontainer">
			<ul id="navlist">

				<li><%= link_to "Home", { :controller => 'static_pages', :action => 'home' }, :class => 'current' -%> </li>
				<li><%= link_to("About Us", '/static_pages/about')%></li>
				<li><%= link_to("Get Involved", '/static_pages/getInvolved')%></li>
				<li><%= link_to("Events", '/static_pages/events')%></li>
				<li><%= link_to("Gallery", '/static_pages/gallery')%></li>
				<li><%= link_to("FAQs", '/static_pages/faqs')%></li>
				<li><%= link_to("Contact Us", '/static_pages/contact')%></li>
			
			</ul>
		</div>
<p>Find me in app/views/static_pages/partners.html.erb</p>